# Generated by Django 5.1.1 on 2024-10-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=200)),
                ('L_name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('working', models.BooleanField(default=True)),
            ],
        ),
    ]
