# Generated by Django 5.1.1 on 2024-10-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='F_name',
            new_name='First_name',
        ),
    ]
